### ISSUE TITLE
Dashboard Mobile Ansicht

### ISSUE THREAD

**Issue by noppelmax** [vspaceone/web#1]
In der Mobilen Ansicht rutschen die beiden Überschriften über die Werte. Die Werte sind dann nicht mehr zu ortenbar. Gesehen auf Android SGS2

**Comment by djesionek** [comment]
Fixed in 20f49255c6934bdf7d9fb42ae26da511d8b7cefd

**Comment by noppelmax** [comment]
Thanks ;)
