### ISSUE TITLE
Footer und Header nicht doppelt implementieren

### ISSUE THREAD

**Issue by noppelmax** [vspaceone/web#15]
Aktuell sind Footer und Header für jede Seite (Impressum, Dashboard, Downloads, ... ) jeweils neu implementiert. Da wir eh schon PHP am laufen haben könnte man das damit umgehen. Ich kann das bei Bedarf mal machen.

**Comment by djesionek** [comment]
@noppelmax Hab mal was zu dem Thema gemacht ist im entsprechenden Branch und auf Beta online. Sollte alles laufen wenn ich nix übersehen habe

**Comment by noppelmax** [comment]
Nice! Danke dir! ;)
