### ISSUE TITLE
3 Bilder auf Mobile

### ISSUE THREAD

**Issue by noppelmax** [vspaceone/web#3]
In der mobilen Ansicht sind die 3 Texte und Bilder auf der "Was haben wir" Seite in der falschen Reihenfolgen. Erst kommen die Texte, dann die Bilder. Gewünscht wäre Text, Bild, Text, Bild, Text Bild. Gesehen auf Android, Firefox, SGS2

**Comment by v0tti** [comment]
Wurde schon länger gefixt, jetzt sind auch die Dateigrößen in einer sinnvollen Größenordnung.
