### ISSUE TITLE
Temperaturen von Brücke also auch Maschinenraum stimmen nicht mehr. 

### ISSUE THREAD

**Issue by noppelmax** [vspaceone/web#32]
Das Dashboard können wir uns also sparen. Oder jemand bringt das wieder zum laufen. @djesionek kann deine Spaceapi Schnittstelle auch Sensorwerte empfangen?

**Comment by djesionek** [comment]
Kann sie. Bis auf weiteres wird eben nichts angezeigt weil es erstmal keine sensoren mehr gibt, die daten sammeln
