### ISSUE TITLE
Events Formatierung und "vergangene"

### ISSUE THREAD

**Issue by noppelmax** [vspaceone/web#35]
- Vergangenen Events ausblenden
- Events vernünftig formatieren. Evtl aus JSON Datei oder Kalender laden.

**Comment by noppelmax** [comment]
![photo_2018-11-19_11-59-08](https://user-images.githubusercontent.com/7629938/48702928-88879500-ebf2-11e8-81fb-7ecd2469b4d3.jpg)

So solls mal aussehen

**Comment by djesionek** [comment]
Würde es erstmal aus einer lokalen JSON Datei anzeigen lassen, in Zukunft können wir vlt eine kleine Eventverwaltung basteln, die das in JSON per API bereitstellt

**Comment by noppelmax** [comment]
Ne JSON Datei wäre ja schon iwie ne Schnittstelle, die völlig ausreicht für uns
